version: "3.8"

services:
  auth-api:
    container_name: auth-api
    build: ./auth-api
    ports:
      - "8080:8080"
    depends_on:
      - auth-db

  account-api:
    container_name: account-api
    build: ./account-api
    ports:
      - "8081:8080"
    depends_on:
      - ib-db
      - auth-api
      - kafka-service
      - mail-service
      - branch-api

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://ib-db:5432/internet-banking -schemas=public -user=postgres -password=postgres -X migrate
    volumes:
      - ./resources/db/migration/:/flyway/sql/
    depends_on:
      - ib-db

  transaction-api:
    container_name: transaction-api
    build: ./transaction-api
    ports:
      - "8082:8080"
    depends_on:
      - ib-db
      - auth-api
      - account-api
      - kafka-service

  auth-db:
    container_name: auth-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
    ports:
      - "5433:5432"

  ib-db:
    container_name: ib-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=internet-banking
    ports:
      - "5434:5432"

  branch-api:
    container_name: branch-api
    build: ./branch-api
    ports:
      - "8085:8080"
    depends_on:
      - ib-db

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
    links:
      - zookeeper

  kafka-service:
    container_name: kafka-service
    build: ./kafka-service
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8083:8080"
    depends_on:
      - kafka

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  mail-service:
    container_name: mail-service
    build: ./mail-service
    ports:
      - "8084:8080"
    depends_on:
      - mail-dev
