version: "3.8"

services:
  auth-api:
    container_name: auth-api
    build: ./auth-api
    ports:
      - "8080:8080"
    depends_on:
      - auth-db

  account-api:
    container_name: account-api
    build: ./account-api
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8081:8080"
    depends_on:
      - ib-db
      - auth-api
      - kafka

  transaction-api:
    container_name: transaction-api
    build: ./transaction-api
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8082:8080"
    depends_on:
      - ib-db
      - auth-api
      - account-api
      - kafka

  auth-db:
    container_name: auth-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
    ports:
      - "5433:5432"

  ib-db:
    container_name: ib-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=internet-banking
    ports:
      - "5434:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    links:
      - zookeeper
