version: '3.9'

services:
  account-api:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
  adminer:
    image: adminer
    ports:
      - "8081:8080"